plugins { id 'com.android.application' }
android {
    namespace 'ru.neon.checker'
    compileSdk 34
    defaultConfig { applicationId "ru.neon.checker"; minSdk 24; targetSdk 34; versionCode 1; versionName "1.0" }
    compileOptions { sourceCompatibility 17; targetCompatibility 17 }
}
dependencies {}
